set nocompatible
filetype plugin indent on
syntax enable

set encoding=utf-8
set number relativenumber
set cursorline cursorcolumn
set showmatch
set wildmenu
set wildmode=longest:full,full
set signcolumn=yes
set colorcolumn=80

set tabstop=8
set shiftwidth=8
set noexpandtab
set autoindent
set smartindent

autocmd FileType python setlocal expandtab tabstop=4 shiftwidth=4
autocmd FileType rust setlocal expandtab tabstop=4 shiftwidth=4
autocmd FileType zig setlocal expandtab tabstop=4 shiftwidth=4
autocmd FileType sh,bash setlocal expandtab tabstop=2 shiftwidth=2
autocmd FileType yaml,yml,json setlocal expandtab tabstop=2 shiftwidth=2

set ignorecase
set smartcase
set incsearch
set hlsearch
nnoremap <silent> <Space> :nohlsearch<CR>

set lazyredraw
set ttyfast
set scrolloff=8
set updatetime=200
set timeoutlen=400

set nobackup
set nowritebackup
set noswapfile
set undofile
set undodir=~/.vim/undo

set splitbelow
set splitright

set laststatus=2
set statusline=%!Statusline()

function! Statusline()
  let l = mode()
  let f = expand('%:f')
  let m = &modified ? '+' : ''
  let r = &readonly ? 'RO' : ''
  let t = &filetype
  let p = printf('%d:%d %d%%%%', line('.'), col('.'), (line('.') * 100) / max([1,line('$')]))
  let paste = &paste ? ' PASTE' : ''

  let git = ''
  if exists('*FugitiveHead')
    let b = FugitiveHead()
    if b !=# ''
      let git = '  ' . b
    endif
  endif

  return printf(' %s %s %s%s %%=%s %s %s%s ',
        \ l, f, m, r, git, t, p, paste)
endfunction



function! FugitiveBranch()
  if exists('*FugitiveHead')
    let b = FugitiveHead()
    return b !=# '' ? ' '.b : ''
  endif
  return ''
endfunction

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

set tags=./tags;,tags;
nnoremap <F12> :!ctags -R --languages=C,C++,Rust .<CR>

highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.\+/

function! KernelCheckpatch()
    execute '!./scripts/checkpatch.pl --no-tree -f %'
endfunction
command! CheckPatch call KernelCheckpatch()

nnoremap <F5> :make<CR>
nnoremap <F6> :make clean<CR>

autocmd FileType rust nnoremap <buffer> <F5> :!cargo build<CR>
autocmd FileType rust nnoremap <buffer> <F6> :!cargo test<CR>
autocmd FileType rust nnoremap <buffer> <F7> :!cargo run<CR>

autocmd FileType zig nnoremap <buffer> <F5> :!zig build<CR>
autocmd FileType zig nnoremap <buffer> <F7> :!zig build run<CR>

function! InsertHeaderGuard()
    let g = toupper(substitute(expand('%:t'), '[^0-9A-Z]', '_', 'g'))
    call append(0, '#ifndef ' . g)
    call append(1, '#define ' . g)
    call append(2, '')
    call append(line('$'), '')
    call append(line('$'), '#endif')
endfunction
autocmd BufNewFile *.h call InsertHeaderGuard()

autocmd BufNewFile *.sh 0put =\"#!/bin/bash\<nl>\"|$

nnoremap <Leader>gb :!git blame -L <C-r>=line('.')<CR>,<C-r>=line('.')<CR> %<CR>
nnoremap <Leader>gs :Git<CR>
nnoremap <Leader>gd :Gdiffsplit<CR>

nnoremap <Leader>ev :edit $MYVIMRC<CR>
nnoremap <Leader>sv :source $MYVIMRC<CR>

cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

set pastetoggle=<F2>

nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>x :x<CR>
nnoremap <Leader>rw :%s/\s\+$//e<CR>

call plug#begin('~/.vim/plugged')

Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'preservim/nerdtree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'dense-analysis/ale'
Plug 'rust-lang/rust.vim'
Plug 'ziglang/zig.vim'
Plug 'vim-scripts/a.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'jiangmiao/auto-pairs'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/tagbar'
Plug 'editorconfig/editorconfig-vim'
Plug 'sheerun/vim-polyglot'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'mbbill/undotree'
Plug 'machakann/vim-highlightedyank'
Plug 'easymotion/vim-easymotion'

call plug#end()

set termguicolors
colorscheme catppuccin_macchiato
let g:airline_theme = 'catppuccin_macchiato'

nnoremap <C-n> :NERDTreeToggle<CR>
nnoremap <C-p> :Files<CR>
nnoremap <Leader>f :Rg<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <F8> :TagbarToggle<CR>
nnoremap <Leader>u :UndotreeToggle<CR>
nmap <Leader><Leader> <Plug>(easymotion-s2)

let g:ale_linters = {
\ 'c': ['clang', 'gcc'],
\ 'rust': ['cargo'],
\ 'python': ['flake8'],
\ 'sh': ['shellcheck'],
\}

let g:ale_fixers = {
\ 'rust': ['rustfmt'],
\ 'python': ['black'],
\}

let g:ale_fix_on_save = 1

let g:rust_fmt_autosave = 1
let g:zig_fmt_autosave = 1

inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1) :
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()

inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

inoremap <silent><expr> <CR>
      \ coc#pum#visible() ? coc#pum#confirm() :
      \ "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let c = col('.') - 1
  return !c || getline('.')[c - 1] =~# '\s'
endfunction

inoremap <silent><expr> <c-space> coc#refresh()

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nmap <leader>rn <Plug>(coc-rename)

nnoremap <silent> K :call ShowDocumentation()<CR>

function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K','in')
  endif
endfunction

if filereadable(expand('~/.vimrc.local'))
    source ~/.vimrc.local
endif

